README.md
demos/S3/run_eureka.py
docs/source/installation.rst
docs/source/quickstart.rst
eureka/S3_data_reduction/bright2flux.py
eureka/S3_data_reduction/nircam.py
eureka/S3_data_reduction/plots_s3.py
eureka/S3_data_reduction/s3_reduce.py
eureka/S4_generate_lightcurves/plots_s4.py
eureka/S4_generate_lightcurves/s4_genLC.py
eureka/S5_lightcurve_fitting/utils.py
eureka/lib/astropytable.py
eureka/lib/readECF.py
eureka/lib/sort_nicely.py
eureka/lib/util.py
eureka/tests/test_S3.py
requirements.txt

Changes:
- Data & dat and Metadata & md are now: DataClass & data and MetaClass & meta
- Note that the raw 2D spectrum is now stored in data.data
- fix in s3_reduce.py: median frame is now being saved in data instead of meta
- when the code is run now, a copy of the ecf file is saved into the workdir (if running S3) or lcdir (if running S4) [I think that's a good idea if the user wants to check which settings he used when running Eureka!]
- added astroquery as a requirement (svo_filters needs it)
- added a note in eureka/S5_lightcurve_fitting/utils.py that the EXOCTK_DATA is only important for Stage 5 [might scare people who only want to run S3 or S4]
- docs: more thorough quickstart 
- run_script.py: commented out all sys.path.append

Changing class and instance name for Data and Meta

---

eureka/S3_data_reduction/nirspec.py
requirements.txt
setup.py

Initial commit to enable Eureka to read in Stage 1 rateints.fits files and process them through the JWST pipeline to Stage 2, whilst avoiding the significant y-axis trimming that is usually performed .

Include the capability to read and process NIRSpec rateints.fits files.

---

eureka/S2_calibrations/__init__.py
eureka/S5_lightcurve_fitting/limb_darkening_fit.py
eureka/lib/plots.py

I created this branch to directly address issue #42 where matplotlib/TeX causes crashes at a variety of different stages in the pipeline depending on the user. 
After some testing, I'm almost certain that the following lines on one of the Stage 5 files has been editing the underlying matplotlib rcParams whenever Eureka is imported, and is directly causing these issues. I've attached some images below of what a plot looks like with and without these lines. Personally, I actually prefer the default matplotlib font, although we might need to make some changes to the font sizes directly in our plotting routines. 
```
rc('font', **{'family': 'sans-serif', 'sans-serif': ['Helvetica'], 'size': 16})
rc('text', usetex=True)
```
@taylorbell57 Could you install this branch and remove the additional …

Update limb_darkening_fit.py to correct matplotlib/TeX errors

---

demos/S2/S2_imaging_template.ecf
demos/S2/S2_miri_lrs_template.ecf
demos/S2/S2_nircam_wfss_template.ecf
demos/S2/S2_nirspec_fs_template.ecf
demos/S2/run_eureka.py
eureka/S2_calibrations/s2_calibrate.py

I have reorganized the S2 code I wrote to allow for the reuse of some code between photometry and spectroscopy modes. I then added a small little wrapper around the STScI's Image2Pipeline that allows the relevant steps to be skipped if requested in the ecf. I've also added a new ecf template for imaging mode observations and slightly tweaked the other templates. I have tested the pipeline step on my simulated MIRI full-frame image as well as my SUB64 simulation, and both worked fine.
This PR resolves Issue #70 (which I closed prematurely having forgotten to make this PR).

Adding photometry to S2

---

eureka/S2_calibrations/s2_calibrate.py
requirements.txt

Alright, I've tested NIRCam, NIRSpec, and MIRI with `jwst` v1.3.3 using these only very minor tweaks. I tested MIRI simulations from the previous ERS challenge as well as some simulations I made with the newest version of MIRISIM that will be used for the upcoming ERS showcase, and both worked well. The constraint on `photutils` comes directly from the requirements of the `jwst` v1.3.3 requirements

Updating to jwst 1.3.3

---

eureka/S5_lightcurve_fitting/models/Model.py

Accidentally wrote `type(Parameters).__name` rather than `Parameters.__name__`

Fixing typo in Models.py

---

README.md
docs/source/faq.rst
docs/source/installation.rst
requirements.txt
setup.py

Now telling people to do pip install rather than calling setup.py
directly which is becoming deprecated and requires extra maintenance
efforts. Also added some help details in the faq page to make sure
people are reading the installation page

Changing installation instructions to pip install

---

.gitignore

Blocking additions to eureka/tests/data by default
Currently people can accidentally upload the outputs from pytest to
GitHub which we don't want. I suggest we add eureka/tests/data to
.gitignore (which I am now doing) and then one must use the -f flag to
force new adds to the tests/data folder

Ignore outputs from pytest

---

demos/JWST/S1_miri_template.ecf
demos/JWST/S1_nirx_template.ecf
docs/media/S1_template.ecf

Without quotation marks, all gets interpreted as the built-in function all. Edited ecf templates to encourage people to use quotation marks. Closes Issue #123

Resolving Issue #123

---

eureka/S3_data_reduction/s3_reduce.py
eureka/S6_planet_spectra/s6_spectra.py

The error message in S3 when no S2 files were found is out-of-date, and this tiny PR fixes that issue

Fixing error message for S3 when no files found

---

eureka/S5_lightcurve_fitting/models/Model.py
eureka/S5_lightcurve_fitting/s5_fit.py

CompositeModel was making an array of ones that had the wrong dimensions for shared fits in the eval-type functions. This bug arose when I made edits in PR #130 and didn't test with a shared fit. This explains the error I encountered in PR #131, although that PR will still have separate issues with shared fits

Resolving shape mismatch for shared fits

---

eureka/S1_detector_processing/ramp_fitting.py
eureka/S4_generate_lightcurves/plots_s4.py
eureka/S4_generate_lightcurves/s4_genLC.py

Added figure 4102, which is nearly identical to 3101, but includes the benefits of drift/jitter correction.  The plot also draws vertical dashed lines to indicate breaks between spectroscopic channels.
To get the drift/jitter correction working, I set the weights to unity for now.  The previous mask was the wrong size.

New 2D light curve with drift/jitter correction

---

demos/JWST/S3_miri_lrs_template.ecf
demos/JWST/S3_nircam_wfss_template.ecf
demos/JWST/S3_nirspec_fs_template.ecf
docs/media/S3_template.ecf
docs/source/ecf.rst
docs/source/quickstart.rst
eureka/S3_data_reduction/bright2flux.py
eureka/S3_data_reduction/miri.py
eureka/S3_data_reduction/nircam.py
eureka/S3_data_reduction/niriss.py
eureka/S3_data_reduction/nirspec.py
eureka/S3_data_reduction/plots_s3.py
eureka/S3_data_reduction/s3_reduce.py
eureka/S5_lightcurve_fitting/fitters.py
eureka/S5_lightcurve_fitting/likelihood.py
eureka/S5_lightcurve_fitting/plots_s5.py
eureka/S6_planet_spectra/s6_spectra.py
eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf
eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf

This PR builds upon #166, so that one should be merged first.
I maintained backwards compatibility with old saved csv chains, but I
now save chains as HDF5 files which are far more compressed and still
independent of programming language.
I also made a much better chain plot to show the evolution of the emcee
walkers with several visual aids. See below for a super-short emcee fit I
just did to the MIRI/LRS phase curve that is obviously nowhere near
burned in, but gives you the general idea of what the plot looks like.
There will be multiple figures if there are more than 12 parameters to
keep the figure size manageable. I'll try to do a longer run to show you
what the chain looks like when it's at least near converged, but those
horizontal dotted lines can be used as rulers to see if the …

Patching bug with plotting chain, saving chain as HDF5

---

eureka/S3_data_reduction/s3_reduce.py

Before, using multiple aperture pairs for MIRI would result in xwindow
and ywindow being rotated for every aperture pair which would cause the
code to crash and give many error messages (e.g. Issue #184). This edit
closes #184

Only rotating xwindow ywindow once

---

demos/HST/S3_wfc3_template.ecf
demos/JWST/S3_miri_lrs_template.ecf
demos/JWST/S3_nircam_wfss_template.ecf
demos/JWST/S3_nirspec_fs_template.ecf
docs/media/S3_template.ecf
eureka/S3_data_reduction/background.py
eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf
eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf

This PR allows background subtracted FITS files to be saved in Stage 3. The FITS files have different shapes since the background subtraction happens after util.trim happens, but at least we'll have something to submit to the ERS data challenge Background-Subtracted Countrate Images folder.

Allow background subtracted FITS files to be saved

---

README.md
requirements.txt

The process for setting the CRDS environment variables also should be outlined in the GitHub readme, otherwise people will probably miss doing this if they don't read the documentation. 
In addition, people like to build local documentation sometimes (either for development or personal reasons), so if they want to do this, they need sphinx-rtd-theme to be installed.

Added CRDS vars to README, added sphinx-rtd-theme to requirements

---

demos/JWST/S4_template.ecf
docs/media/S4_template.ecf
docs/source/ecf.rst
eureka/S4_generate_lightcurves/s4_genLC.py
eureka/tests/NIRCam_ecfs/S4_NIRCam.ecf
eureka/tests/NIRSpec_ecfs/S4_NIRSpec.ecf

Automatically sets the wave_min and wave_max values to the min and max
of the extracted spectra if the values are None in the S4 ecf.
I've confirmed that this still passes the pytest tests.

Resolve #182 by auto setting wave_min/max if None

---

requirements.txt

This was added by Adina for an older jwst version and is no longer
needed.
This resolves #197

Removing requirement for astropy<5.0.0

---

eureka/S2_calibrations/s2_calibrate.py
eureka/S4_generate_lightcurves/plots_s4.py
eureka/S5_lightcurve_fitting/plots_s5.py

Rather than opening Fig4300, Fig4301, Fig4302, etc., just open a Fig4300
with plt.figure and then overwrite that figure as needed to avoid
excessive RAM usage. This does not change the output filename, just
reduces the number of plots we open.

Only one plt.figure per type, overwrite if need

---

eureka/S3_data_reduction/miri.py
eureka/S4_generate_lightcurves/s4_genLC.py
eureka/S5_lightcurve_fitting/s5_fit.py
eureka/lib/clipping.py

I needed to add a new time array for the newest MIRI simulations. I also needed more flexibility in the sigma clipping due to the strong ramp in MIRISIM_TSO simulations. Finally, S5 now simultaneously fits 2 wavelengths if testing_S5==True and any of the fit_par ecf values are 'shared'

Some tweaks for the newest NGTS-10b simulation with a companion star

---

.github/ISSUE_TEMPLATE/bug-template.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/first-template.yml
.github/workflow/assign-issue.yml

Hey, @kevin218, this is my first attempt at making an issue template. What I'm trying to set up now is a workflow script that will automatically assign an issue to different people based on whether the issue is submitted for one of the four instruments or for general lightcurve fitting. However, after setting this up I realized I can only view the template and test it out if it's merged into the main branch. Would you be ok with going ahead and merging this? I promise I won't make changes to any of the other files. :)

Issue template

---

eureka/S5_lightcurve_fitting/fitters.py

The most recent PR for the GP code included a tab instead of four spaces in one place of the fitters.py file which breaks even importing eureka (or at least importing Stage 5 code).

Undoing bug introduced by GP PR

---

eureka/S5_lightcurve_fitting/models/Model.py

Previously the GPeval function would return all ones if a GP was not being used. Because the GP model is additive rather than multiplicative, this messed up the reduced chi-squared calculation but other parts of the code did not end up using the GPeval function so they were fine.
Resolves #253.

Fixing reduced chi-squared calculation

---

eureka/S3_data_reduction/hst_scan.py
setup.py

Previously I'd forgotten to not throw an error about missing
image_registration if WFC3 analyses were not being performed.

image_registration is now truly optional

---

eureka/S3_data_reduction/__init__.py

I accidentally added niriss_cython even though it shouldn't be imported
directly

Removing niriss_cython import

---

setup.py

Installing Eureka! is currently failing due to a small error in `setup.py`. According to [PEP 508](https://peps.python.org/pep-0508/) syntax, the line 
`'hst': ["git+https://github.com/keflavich/image_registration.git"]`
should be changed to:
`'hst': ["image_registration @ git+https://github.com/keflavich/image_registration.git"]`

Closes #292 by fixing syntax for extras_require in setup.py

---

demos/JWST/S5_fit_par_template.epf
demos/JWST/S5_template.ecf
eureka/S5_lightcurve_fitting/likelihood.py
eureka/S5_lightcurve_fitting/models/GPModel.py
eureka/S5_lightcurve_fitting/s5_fit.py
requirements.txt
tests/NIRCam_ecfs/S5_NIRCam.ecf
tests/NIRSpec_ecfs/S5_NIRSpec.ecf

- Some changes to parameters and how they are read in to be able to support shared parameters within the GP. 
- Added the gp package celerite and runs fine on individual channels, but I wasn't able to fully run with shared fits so it might be buggy still. 
- Also fixed that the lc.unc_fit is used within the GP model as the noise instead of lc.unc. 
- (There have also been some changes to the tinygp code but it doesn't work just yet so I need to do this for the next release.)

Add celerite as a gp package and abillity for shared parameters

---

demos/HST/run_eureka_wfc3.py
demos/JWST/run_eureka.py
eureka/S1_detector_processing/s1_process.py
eureka/S2_calibrations/s2_calibrate.py
eureka/S3_data_reduction/background.py
eureka/S3_data_reduction/miri.py
eureka/S3_data_reduction/plots_s3.py
eureka/S3_data_reduction/s3_reduce.py
eureka/S4_generate_lightcurves/plots_s4.py
eureka/S4_generate_lightcurves/s4_genLC.py
eureka/S5_lightcurve_fitting/lightcurve.py
eureka/S5_lightcurve_fitting/modelgrid.py
eureka/S5_lightcurve_fitting/models/Model.py
eureka/S5_lightcurve_fitting/plots_s5.py
eureka/S5_lightcurve_fitting/s5_fit.py
eureka/S5_lightcurve_fitting/utils.py
eureka/S6_planet_spectra/plots_s6.py
eureka/S6_planet_spectra/s6_spectra.py
eureka/lib/manageevent.py
eureka/lib/medstddev.py
eureka/lib/readECF.py
eureka/lib/readEPF.py
eureka/lib/util.py
tests/test_MIRI.py
tests/test_NIRCam.py
tests/test_NIRSpec.py
tests/test_WFC3.py
tests/test_general.py
tests/test_lightcurve_fitting.py

Alright, I've now cleaned up the way that stages are connected, so we no longer have weird behaviours if folders get renamed between stages. To do this, I moved the different aperture folders from Stages 3+ into a single folder for that stage (e.g. Stage3/S3_2022-04-25_miri_run1/ which contains the folders ap4_bg5 and ap4_bg10, and similarly for Stages 4-6).
I also wanted to be able to try Eureka! on Windows which uses back slashes instead of forward slashes, so I updated all the slashes to os.sep which figures out whether to use forward or back slashes.
I've run the code through all the tests successfully and manually tested it as well.

Changing the way inputdir is auto completed

---

eureka/lib/readEPF.py
tests/test_lightcurve_fitting.py

Resolves one of the issues encountered in #319 by giving the user a
helpful warning if their EPF file does not exist rather than waiting
until the EPF is copied and crashing because self.filename is not
defined.

Add helpful FileNotFoundError if EPF doesn't exist

---

demos/JWST/S5_fit_par_template.epf
demos/JWST/run_eureka.py
docs/source/quickstart.rst
eureka/S5_lightcurve_fitting/fitters.py
eureka/S6_planet_spectra/s6_spectra.py

The EPF template was still optimized for NIRCam simulations and had several issues for the NIRSpec tiny dataset used in the quickstart guide. The updated values resolve #326
I also edited the quickstart guide to explain run_nlive and have users edit it during the quickstart so they understand how to do so. This also helps make the quickstart quicker to run by a factor of a few for Stage 5 at the cost of a fairly unimportant degredation to the corner plot.
Finally, I also changed the order of S5 outputs for easier debugging. Specifically, I moved the S5 outputs that are most likely to fail (e.g. corner plot) to the end of each fitter function and moved the most helpful outputs for debugging (e.g. text logging, simpler plots) to earlier on.

Fixing bugs with quickstart

---

.readthedocs.yaml
docs/source/copyright.rst
docs/source/index.rst
requirements.txt
setup.py

Because Astraeus requires a specific python version that is not consistent with the readthedocs default, the docs page has been failing to build since we added Astraeus to Eureka. This is now fixed with a new .readthedocs.yaml file which I have confirmed works on the readthedocs webpage (https://eurekadocs.readthedocs.io/en/fixing-docs/index.html).
Also adding Yoni who was missing from the copyright page and tweaking the phrasing of the Stage 4 description in docs index.

Fixing docs with new .readthedocs.yaml file

---

eureka/S5_lightcurve_fitting/fitters.py

Fixed a typo in calculating the autocorrelation time with emcee that made it never output an autocorrelation time

fitters.py bug fix

---

.gitignore
demos/JWST/S6_template.ecf
docs/media/S6_template.ecf
docs/source/ecf.rst
eureka/S1_detector_processing/s1_process.py
eureka/S2_calibrations/s2_calibrate.py
eureka/S3_data_reduction/miri.py
eureka/S3_data_reduction/nircam.py
eureka/S3_data_reduction/nirspec.py
eureka/S4_generate_lightcurves/plots_s4.py
eureka/S4_generate_lightcurves/s4_genLC.py
eureka/S5_lightcurve_fitting/s5_fit.py
eureka/S6_planet_spectra/plots_s6.py
eureka/lib/readECF.py
eureka/lib/util.py
tests/MIRI_ecfs/S6_MIRI.ecf
tests/NIRCam_ecfs/S6_NIRCam.ecf

This PR resolves #320 (allow setting of S6 model zorder) and resolves #337 (NaN uncertainties going into S5 fits). It also updates now out-of-date Stage 1 code that was broken when files were updated in the lib folder - we didn't catch that earlier since we don't have tests for Stage 1. I've also more generally fixed the `EurekaSpec2Pipeline has no attribute master_background` issue by first checking that such a step exists - this will also resolve the same issue Adina found for NIRISS but do so for all instruments (since I just encountered it on MIRI data). I also fixed a bug in Stage 4 clipping where `lc.wave_mid.attrs['wave_units']` was undefined.
I also now made it so that the bin edges are always plotted in Fig 4101 while they were previously only plotted if there was more than one …

Bug fixes and new features

---

eureka/S1_detector_processing/s1_process.py
eureka/S2_calibrations/s2_calibrate.py
eureka/S3_data_reduction/s3_reduce.py
eureka/S4_generate_lightcurves/s4_genLC.py
eureka/S5_lightcurve_fitting/s5_fit.py
eureka/S6_planet_spectra/s6_spectra.py
eureka/lib/util.py
tests/test_MIRI.py
tests/test_NIRCam.py
tests/test_NIRSpec.py
tests/test_WFC3.py

Resolves #339
I thought about setting meta.datetime elsewhere, but I wanted to avoid
setting it multiple times per stage (e.g. once per aperture pair) in
case analyses are being run near midnight
I also renamed the imported package `time` to `time_pkg` as its name
all too often conflicts with a local variable for the observation times

Set meta.datetime once at the start of every stage

---

eureka/S3_data_reduction/nirspec.py

The values are not defined for the simulations, so they should be inside
a try/except which they are, but they were also duplicated outside of
the try/except.
Thanks to Erin May for pointing this out!

Fixing bug with instart and intend for NIRSpec

---

src/eureka/S4_generate_lightcurves/s4_genLC.py

At some point the error calculation was messed up in S4, and the error
estimates were far too low. The issue was that the errors were being
divided by the total number of unmasked data points rather than the
number of unmasked data points used for that wavelength channel

Fixing error calculation bug in S4

---

docs/source/installation.rst
docs/source/quickstart.rst

I've updated the installation page on the docs to reflect that we want users to install the v0.1-alpha stable release. This was pretty simple, you just pass the release tag to the git repo address as if it's a specific branch.
I've also fixed some minor wording issues and rearranged the installation instructions to more clearly distinguish between setting up a Conda environment, then using git/pip to download and install Eureka! from downloading Eureka! and then using the environment.yml file to set up the environment.

Update installation docs for stable release v0.1-alpha

---

demos/HST/download_data_HST_template.py
setup.cfg
src/eureka/lib/mastDownload.py

This PR adds two files: 
- mastDownload.py is a wrapper for astroquery.mast.Observations that is geared towards downloading and organizing exoplanet data acquired by HST.
- download_data_HST_template.py provides a demo of how to download HST data.  It is a script that can be edited and run locally.

Add ability to download HST data using MAST API

---

demos/HST/S3_wfc3_template.ecf
demos/JWST/S3_miri_lrs_template.ecf
demos/JWST/S3_nircam_wfss_template.ecf
demos/JWST/S3_nirspec_fs_template.ecf
docs/media/S3_template.ecf
docs/source/ecf.rst
environment.yml
setup.cfg
src/eureka/S1_detector_processing/ramp_fitting.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S3_data_reduction/source_pos.py
src/eureka/S3_data_reduction/wfc3.py
tests/MIRI_ecfs/S3_MIRI.ecf
tests/NIRCam_ecfs/S3_NIRCam.ecf
tests/NIRSpec_ecfs/S3_NIRSpec.ecf
tests/WFC3_ecfs/S3_WFC3.ecf
tests/__init__.py

This PR updates the `jwst` package version from 1.3.3 to the latest 1.6.0 (resolves #335). In addition, for newer versions of `jwst` than 1.3.3 we don't need to specify an `asdf` version number (that was just a bug with `jwst` 1.3.3), so I removed that version number.
The main reason we couldn't do this before is that newer versions of the `jwst` pipeline broke for the NIRSpec simulations (see Issue #165). I found that this could be quickly resolved by allowing the value in the FITS header to be overridden using the source_pos function which already exists. Previously, if the FITS header had a SRCYPOS value, you had to use it, but now that behaviour is only the case if `meta.source_pos_type='header'`. Moving forward, I think if we want to use the SRCYPOS value with subarray observations …

Updating jwst package version to 1.6.0

---

src/eureka/S5_lightcurve_fitting/fitters.py

The start_from_oldchain_emcee function was broken when we changed the
format of the fitparams csv save file. This patch fixes that and allows
users to resume an emcee fit from an old chain.

Fixing the start_from_oldchain_emcee function

---

src/eureka/S1_detector_processing/s1_process.py
src/eureka/S2_calibrations/s2_calibrate.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/lib/util.py

Because of an update I made to util.readfiles, an unhelpful error
message would be raised if no files were found. This patch reduces
duplicated code between S1-3 and raises a better message if no
files are found

More useful error message if no FITS files found

---

src/eureka/S3_data_reduction/miri.py
src/eureka/S3_data_reduction/nircam.py
src/eureka/S3_data_reduction/nirspec.py

We incorrectly guessed that each segment would have the whole time
array. Each segment only has the time values for that segment, so no
need to crop the arrays

Fixing time arrays for real data

---

src/eureka/S2_calibrations/s2_calibrate.py
src/eureka/S3_data_reduction/bright2flux.py

I realized that the MIRI gain file was being rotated 90 degrees like the data, but was not then being mirrored along the new x-axis to have wavelength increasing to the right like the data array. While I was at it, I fixed the two minor flake8 issues that were recently introduced

Fixing MIRI gain file

---

demos/JWST/S5_fit_par_template.epf
docs/media/S5_fit_par_template.epf

Previously the EPF template used scatter_ppm because there was a bug
the estimated noise from S4, but that has since been fixed, and users
should use scatter_mult instead as it is far more robust and less prone
to user error.

Tweaking S5 EPF template to use scatter_mult

---

environment.yml

exotic-ld is not hosted on conda, so it must be installed using pip
Discovered in issue #415

Fixing exotic-ld installation in environment.yml

---

demos/JWST/S4_template.ecf
demos/JWST/S5_template.ecf
docs/source/faq.rst
docs/source/installation.rst
docs/source/quickstart.rst

Noting to use environment.yml on M1 processors: resolves #415 and resolves #421
Fixing small typo in quickstart: resolves #422

M1 installation instructions and quickstart typo

---

src/eureka/S1_detector_processing/ramp_fitting.py

Removed int_times from ramp_fit_mean() in ramp_fitting.py to fix bug described in Issue #443 .
2 'test' runs finished with no errors. A real run on a full data set completed and the results look as expected.

Removed int_times from ramp_fit_mean

---

docs/source/faq.rst

adds a reminder to the faqs to source the shell profile to make sure the CRDS environment variables are found

add faq about CRDS error

---

src/eureka/S5_lightcurve_fitting/s5_fit.py

this PR fixes a bug in S5 for manually clipping data points. The lc and meta arrays are now updated when the manual_clip function is called in s5_fit.py

fix manual clip bug in S5

---

src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/lib/util.py

Resolves #457
This PR adds a warning to users that they're using pixels that do not have a wavelength solution. This also adds an extrapolation to the NaN wavelengths for Figure 3101 just for plotting purposes. I found that a cubic spline was able to perfectly predict the wavelength solution of two wavelengths artificially set to NaN for MIRI data.

Handling S3 NaN wavelengths

---

src/eureka/lib/mastDownload.py

Previously mastDownload would break if one of table or table2 was empty
(basically always). This PR fixes MAST querying for JWST.

Fixing mastDownload for empty table/table2

---

docs/source/quickstart.rst

The link syntax was wrong for the `exotic-ld` ancillary files.
Ref: https://github.com/openjournals/joss-reviews/issues/4503

Fix tiny typo in Quickstart

---

docs/source/ecf.rst
src/eureka/S1_detector_processing/ramp_fitting.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S3_data_reduction/miri.py
src/eureka/S3_data_reduction/nircam.py
src/eureka/S3_data_reduction/optspex.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S3_data_reduction/sigrej.py
src/eureka/S4_generate_lightcurves/s4_genLC.py
src/eureka/S5_lightcurve_fitting/models/KeplerOrbit.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
src/eureka/S6_planet_spectra/s6_spectra.py
src/eureka/lib/logedit.py
src/eureka/lib/readECF.py
src/eureka/lib/smooth.py
src/eureka/lib/util.py

This PR does the following:
1. Fills the MIRI wavelength array in Stage 3 if the extract_1d step was skipped in Stage 2 (which greatly speeds up Stage 2). With our current version of the jwst pipeline, the wavelength array only gets created if extract_1d is run and even then it just gets filled with zeros. This Stage 3 tweak takes care of both of those situations and will end up doing nothing once we upgrade to a jwst version that properly fills the wavelength array in Stage 2.
2. Adds a few more wavelengths to the NIRCam photometery code to allow different observing parameters
3. Reduces the number of repeated log statements for photometry (now only logged for the first integration per segment which keeps the noise down).
4. Allows the `nplots` ECF parameter to work for the photometry …

Minor convenience improvements

---

environment.yml
setup.cfg

I found that upon doing a clean install with v0.6 I was getting the following error about bokeh not having some required packages set up the right way:
ImportError: cannot import name 'Panel' from 'bokeh.models.widgets' 
It looks like this problem is because the default install now installs bokeh v3.0.1, while previously Eureka! had been automatically installing v2.4.3. I'm not sure if it definitely needs to be v2.4.3 or just <v3.0, but I added a strict requirement for the version. We can change that to an upper limit if you think it would be better though!

Quick bokeh bug fix

---

src/eureka/lib/manageevent.py

The old mergeevent code can be greatly simplified which also has an important on how Evie and Megan are wanting to interact with Eureka for the ERS notebook. Importantly, this function no longer re-loads the ECF file and just uses the already read-in ECF values

Remove unnecessarily complicated mergeevent steps

---

docs/source/installation.rst
environment.yml

Resolves #497
Adding setuptools_scm to environment.yml is needed to properly set the Eureka version number. Successfully tested with Docker to ensure a fresh installation environment (I hadn't noticed this as I had a cached version.py file from doing pip install previously)

Adding setuptools_scm to environment.yml

---

demos/JWST/S4_template.ecf
environment.yml
environment_pymc3.yml
setup.cfg
src/eureka/S1_detector_processing/group_level.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S3_data_reduction/background.py
src/eureka/S3_data_reduction/miri.py
src/eureka/S3_data_reduction/optspex.py
src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/straighten.py
src/eureka/S4_generate_lightcurves/generate_LD.py
src/eureka/S4_generate_lightcurves/s4_genLC.py

This PR enables group-level background subtraction for MIRI.  However, the spectra are cleaner when GLBS is **NOT** used, so I wouldn't recommend people apply this step with MIRI data.  
Fortunately, I was able to get plots_s3.image_and_background() working when using GLBS, so that's a small win.

Enable GLBS for MIRI, fix GLBS plotting

---

demos/JWST/S3_miri_lrs_template.ecf
demos/JWST/S3_nircam_wfss_template.ecf
demos/JWST/S3_nirspec_fs_template.ecf
demos/JWST/S4_template.ecf
demos/JWST/S5_template.ecf
docs/source/ecf.rst
src/eureka/S3_data_reduction/miri.py
src/eureka/S3_data_reduction/nircam.py
src/eureka/S3_data_reduction/nirspec.py
src/eureka/S3_data_reduction/optspex.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/lib/util.py
tests/MIRI_ecfs/S3_MIRI.ecf
tests/NIRCam_ecfs/S3_NIRCam.ecf
tests/NIRSpec_ecfs/S3_NIRSpec.ecf

Instead of only performing outlier rejection along the time axis within the BG region, this added functionality allows the user to perform outlier rejection on the entire frame.  This step (when enabled) takes place before computing the median frame, so has the potential to yield a more reliable median frame.  The risk is that, for deep transits, this routine could flag in-transit points as bad. So, this method should be used with caution.
I have updated the demos and test directories, but not the html file.

Add full frame outlier rejection capabilities

---

src/eureka/lib/citations.py
src/eureka/lib/util.py
tests/test_Photometry_NIRCam.py

Added citation to Schlawin+ (2023) describing NIRCam Photometry (https://ui.adsabs.harvard.edu/abs/2023PASP..135a8001S). Added citation checking to test_Photometry_NIRCam.

Added NIRCam Photometry citation (Schlawin+ 2023)

---

demos/JWST/S1_nirx_template.ecf
demos/JWST/S4_template.ecf
docs/media/S1_template.ecf
docs/media/S4_template.ecf
docs/source/ecf.rst
src/eureka/S1_detector_processing/bias_sub.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S1_detector_processing/superbias.py
src/eureka/lib/astropytable.py

This PR modifies/overrides the JWST pipeline's superbias step (within Stage 1) to apply a scale factor correction.  There are numerous options available in the ECF that can be applied, but the general procedure is the same.  The code always computes a scale factor (SF) correction as follows: SF = (median of group)/(median of superbias), using a background region that is `meta.expand_mask`  pixels from the measured trace.  Depending on `meta.bias_correction` (options include: mean, group_level, smooth, None) `and meta.bias_group` (options include: 1, 2, ..., each), the code applies various corrections to the superbias before subtracting from the data.

Bias Correction

---

src/eureka/S2_calibrations/s2_calibrate.py
src/eureka/S3_data_reduction/straighten.py
src/eureka/S5_lightcurve_fitting/differentiable_models/CentroidModel.py
src/eureka/S5_lightcurve_fitting/differentiable_models/ExpRampModel.py
src/eureka/S5_lightcurve_fitting/differentiable_models/PolynomialModel.py
src/eureka/S5_lightcurve_fitting/differentiable_models/SinusoidPhaseCurve.py
src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py
src/eureka/S5_lightcurve_fitting/differentiable_models/StepModel.py
src/eureka/S5_lightcurve_fitting/models/BatmanModels.py
src/eureka/S5_lightcurve_fitting/models/CentroidModel.py
src/eureka/S5_lightcurve_fitting/models/ExpRampModel.py
src/eureka/S5_lightcurve_fitting/models/PolynomialModel.py
src/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
src/eureka/S5_lightcurve_fitting/models/StepModel.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
src/eureka/lib/split_channels.py

The latest PR unfortunately introduced some glaring bugs which I didn't catch myself nor did the automated tests.
1. Because of the way I implemented the new `meta.nints` code, unshared fits would break after fitting for the first lightcurve.
2. SinusoidalPhaseCurve fits would break with the PyMC3 version of the code as `chan` was always used but not always defined.
3. Also, at present, setting waverange_start and waverange_end to None causes a crash for NIRSpec spectra which shouldn't happen. Users should be able to use the default extraction if they want (or need).
Aside from resolving these bugs, I added a bit nicer formatting for the log statements inside straighten.py.

Bug patches after latest PR

---

environment.yml
environment_pymc3.yml
setup.cfg
src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py
src/eureka/S5_lightcurve_fitting/gradient_fitters.py
src/eureka/S5_lightcurve_fitting/lightcurve.py
src/eureka/S5_lightcurve_fitting/likelihood.py
src/eureka/S5_lightcurve_fitting/models/Model.py
src/eureka/S5_lightcurve_fitting/plots_s5.py

Working with datasets that have many integrations makes it difficult to see what's going on in the light curve plots.  So, when `meta.nbin_plot` is given, the light curves in all figures are now binned to the desired time resolution.  Before, only some plots were binned.
I also updated the `jwst` version to 1.8.2.  Version 1.9 appears to still be buggy.

Enable Binned LC Plots

---

src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S5_lightcurve_fitting/plots_s5.py
src/eureka/lib/centerdriver.py
src/eureka/lib/gaussian_min.py

Corrected plotting features, addressed edge cases with the mgmc centroiding method, and cleaned up formatting.
----
-Added dashed zero lines to fig.3109 to help identify if any slopes occur.
Before:
---
after:
---
-Reformatted fig.3503 to display and corrected 1D gaussians to source in x and y directions.
Before:
---
After:
---
-Corrected labeling in fig.3507 to display batch values instead of segment values.
-Tweaked s3_reduce.py to remember the first median frame for centroiding method to address issues where a new batch could have a bad start frame for the primary centroid guess causing the position to drift over time.
-Renamed the initial centroiding guess position variable for the mgmc method to address issues with position variable being over written by fgc position.
-Changed font …

Corrected issues with mgmc centroiding, cleaned up formatting, and corrected plotting features.

---

demos/JWST/S1_nirx_template.ecf
demos/JWST/S2_nircam_wfss_template.ecf
demos/JWST/S3_nircam_wfss_template.ecf
docs/source/ecf.rst
src/eureka/S1_detector_processing/bias_sub.py
src/eureka/S1_detector_processing/group_level.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S2_calibrations/s2_calibrate.py
src/eureka/S3_data_reduction/background.py
src/eureka/S3_data_reduction/nircam.py
src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S3_data_reduction/source_pos.py
src/eureka/S5_lightcurve_fitting/fitters.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
tests/NIRCam_ecfs/S3_NIRCam.ecf

This resolves #522 by skipping a bunch of unnecessary steps in bias_sub.py when `meta.bias_correction is None`.

Skip masking trace, etc when bias_correction is None; enable row-by-row BG subtraction; edit NIRCam extraction height

---

src/eureka/S3_data_reduction/wfc3.py
src/eureka/S4_generate_lightcurves/wfc3.py
src/eureka/lib/util.py
tests/WFC3_ecfs/S3_WFC3.ecf
tests/WFC3_ecfs/S4_WFC3.ecf

Resolves #304
Previously, the MAD was computed along the wavelength axis and then an average value was computed. Minimizing this 2D MAD is essentially minimizing noise in the spectral direction. Instead, we typically want to minimize noise in the temporal direction, so I've rotated the MAD calculation so that it is computed along the time axis for each wavelength, and then averaged. I also separately handle each WFC3 scan direction to avoid issues there.
I also had to fix a couple of WFC3-related bugs and testing issues in order to get the tests to pass (resolves #542 and other unsubmitted bugs).

Changing the MAD computation direction

---

docs/source/ecf.rst
setup.cfg
src/eureka/S1_detector_processing/bias_sub.py
src/eureka/S1_detector_processing/group_level.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S1_detector_processing/update_saturation.py
src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S4_generate_lightcurves/generate_LD.py
src/eureka/S4_generate_lightcurves/s4_genLC.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
src/eureka/S6_planet_spectra/s6_spectra.py
src/eureka/lib/readECF.py

This PR:
- Makes minor cosmetic changes to several log statements
- Removes the h5py upper limit which is no longer needed and breaks python>3.9 installs
- Avoids over-writing ypos and ywidth plots (figs 3104 & 3105) when there are multiple segments (resolves #528)
- Resolves #537 by removing the bug-inducing and unnecessary `wave_1d_trimmed` variable
- Resolves #521 by moving the `self.superbias = Eureka_SuperBiasStep()` line earlier
- Resolves #501 by reshaping `ld_coeffs` for for input LD files for white lightcurves.
- Makes progress on #540, but we should still add documentation about exotic-ld on the installation instructions page
- Resolves #531 by further clarifying the `manual_clip` index convention
- Resolves #476 by helping users understand how to get access to longer or shorter …

Several bug fixes

---

demos/HST/download_data_HST_template.py
docs/source/ecf.rst

Edited the demo HST MAST download script to remove the call to `sortHST()` that splits up the direct images and spectra into different directories. Also edited the S3 ECF docs page to remove text that implies these should be split up into sci and cal directories, and clarified they should be in the same directory. This should remove any confusion by new HST users (and me, after several weeks of not thinking about HST).
Should we also remove `sortHST()` as a function? Probably not, right?

Edit DL script to put HST files in same directory.

---

docs/source/installation.rst

The current pip installation method using egg= raises a warning about a deprecation that is coming with pip version 25.0. To get ahead of that, let's change things now.
The warning that is currently raised is:
> DEPRECATION: git+https://github.com/kevin218/Eureka.git@dev/tjb#egg=eureka[jwst] contains an egg fragment with a non-PEP 508 name pip 25.0 will enforce this behaviour change. A possible replacement is to use the req @ url syntax, and remove the egg fragment. Discussion can be found at https://github.com/pypa/pip/issues/11617

Updated install instructions to fix deprecation

---

src/eureka/S5_lightcurve_fitting/differentiable_models/__init__.py
src/eureka/S5_lightcurve_fitting/models/__init__.py

The various `__init__.py` files in `S5/models` and `S5/differentiable_models` needed to have the actual HST ramp models specified so they could be used when fitting WFC3 data. I also added the KeplerOrbit as that wasn't available either, but I have not actually tried to use that orbit model and just assumed it was an oversight.

Add HSTRampModel to __init__ for proper importing

---

src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py

So Eric Agol pointed out to Mark Hammond who pointed out to me that by default `starry` doesn't account for light travel time. Back before version 1.0 I knew `starry`had accounted for this but I didn't check the newer version, and apparently with v>=1.0 it doesn't by default. This tiny little PR flips that switch within `starry` to account for light travel time

Accounting for light travel time in starry model

---

docs/source/ecf.rst
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S2_calibrations/s2_calibrate.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S4_generate_lightcurves/s4_genLC.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
src/eureka/S6_planet_spectra/s6_spectra.py
src/eureka/lib/readECF.py

To help strengthen reproducibility and to allow users to manually control the used pmap, we now (silently) log the Eureka! version for Stages 1-6 and the CRDS pmap from Stages 1-3 (4-6 aren't relevant). For all future analyses, warnings will be printed to the terminal if the Eureka! version or CRDS pmap changes (only in the relevant stages), but this will not apply to previous partial reductions of the data (e.g., running the new code on v0.10 Stage 1 files won't raise any pmap or Eureka! version warnings).

Logging Eureka! version and CRDS pmap

---

demos/HST/S3_wfc3_template.ecf
demos/JWST/S3_miri_lrs_template.ecf
demos/JWST/S3_miri_photometry_template.ecf
demos/JWST/S3_nircam_photometry_template.ecf
demos/JWST/S3_nircam_wfss_template.ecf
demos/JWST/S3_nirspec_fs_template.ecf
docs/media/S3_template.ecf
docs/source/ecf.rst
src/eureka/S3_data_reduction/s3_reduce.py

Before this PR, a different median frame was computed for each batch. For those like me who always only a single huge batch, this bug was absent. However, if you used more than one batch (e.g. had too little RAM to load all segments at once), then sometimes things like the computed centroid or curvature correction would change between different segments which would cause jump discontinuities between segments
This partially resolves Issue #538, although I still need to add an override option to the ECF

Default to only compute median frame for 1st batch

---

demos/HST/S5_wfc3_template.ecf
demos/JWST/S5_template.ecf
docs/media/S5_template.ecf
docs/source/ecf.rst
src/eureka/S3_data_reduction/source_pos.py
src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py
src/eureka/S5_lightcurve_fitting/models/BatmanModels.py
src/eureka/S6_planet_spectra/s6_spectra.py

This PR resolves #602 by removing the log which cannot be pickled for multiprocessing. The log wasn't really needed anyway, so this was an easy fix.
This PR also fixes a small nuance in how the S6 final spectra are computed since we were previously using sigmas but should be using percentiles which are more robust to non-Gaussian posteriors. I also slightly tweaked how some parameters were loaded in S6 which will become more important as we add more and more fitted parameters (the old code could sometimes get confused in some edge cases).
Finally, this PR allows users to choose whether or not to apply the light travel time correction. This allows backwards compatibilty with old code while also permitting more user freedom. This new S5 ECF parameter has been noted in the docs and has …

Fixing S3 Pickling Bug, S6 Plotting Bug, and Adding S5 LTT Option

---

.github/workflows/pytest_testing.yml
demos/HST/S4_wfc3_template.ecf
demos/HST/s5_fit_par_wfc3_template.epf
docs/source/ecf.rst
setup.cfg
src/eureka/S3_data_reduction/hst_scan.py
src/eureka/S3_data_reduction/nirspec.py
src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S3_data_reduction/wfc3.py
src/eureka/S5_lightcurve_fitting/models/HSTRampModel.py

This PR implements a few, unrelated enhancements based on my needs while working on several projects over the past week.  Fitting LCs to HST WFC3 data is now less sensitive to HST's period because, by adding h6, the reset now happens during Earth occultation instead of at the time of the first science frame.  This PR also solves an issue reported in #570 in a slightly different manner than @taylorbell57's solution because I wanted to get the half-pixel edges correct (bounds for detector pixels 5-28 need to be 4.5-28.5).  Here's a brief list of fixes:
- Enable HST FLT reduction
- Enhance HSTRampModel
- Update WFC3 template
- Implement `plots_s3.get_bounds()` to correctly define xlim and ylim while accounting for instrument and half-pixels offsets
- Enable calibrated spectra with NIRSpec
- …

Assorted HST and JWST enhancements

---

.gitignore
docs/source/faq.rst
environment_pymc3.yml
setup.cfg

This resolves #586 by only installing `opencv-python-headless` and not `opencv-python`. I also added instructions about resolving `g++` related issues to the FAQ page and explained what to do if folks end up encountering this libGL ImportError issue anyway (e.g., they install `opencv-python` themselves, or another dependency does)

Resolved libGL ImportError by removing opencv-python dependency

---

environment.yml
environment_pymc3.yml
setup.cfg
src/eureka/S5_lightcurve_fitting/plots_s5.py
tests/MIRI_ecfs/S5_MIRI.ecf
tests/NIRCam_ecfs/S5_NIRCam.ecf

This PR resolves #590
Our Allan variance plots so far have been slightly inaccurate and were also lacking uncertainties. This simple little PR adds in those features using the excellent `mc3` utility developed by Patricio and draws some inspiration from code I'd previously written for SPCA.

Computing uncertainty on Allan variance plots using mc3 package

---

demos/JWST/S1_miri_template.ecf
demos/JWST/S1_nirx_template.ecf
docs/media/S1_template.ecf
docs/source/ecf.rst
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S5_lightcurve_fitting/__init__.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
tests/MIRI_ecfs/S1_MIRI.ecf

This little PR parallelizes the Stage 1 Jump Step (an option long offered by STScI's jwst pipeline but not supported by us for some reason). I also tweaked the MIRI S1 template to reflect the best settings I've found from multiple analyses so far. Finally, I also reduced the frequency of the warnings about pymc3/starry not being installed (which others have complained about), and now these will only pop up when the user tries to use the packages and causes an informative `AssertionError`.

Stage 1 Jump Step Parallelization

---

environment.yml
environment_pymc3.yml
setup.cfg
src/eureka/S5_lightcurve_fitting/fitters.py
src/eureka/S5_lightcurve_fitting/models/GPModel.py
src/eureka/lib/gaussian_min.py
tests/NIRSpec_ecfs/S5_NIRSpec.ecf
tests/NIRSpec_ecfs/S5_fit_par.epf
tests/test_NIRSpec.py

This RP resolves #608
This will later allow us to use celerite2 with PyMC3 fitters/models, and also fixes some annoying bugs caused by celerite. I also added a test of the GP model to the NIRSpec lsq fitting test to get some more coverage of the code. Finally, I also switched the default lsq fitter to Powell instead of Nelder-Mead since I have indeed found that Powell is more performant.

Switching from celerite to celerite2

---

demos/HST/S4_wfc3_template.ecf
demos/JWST/S4_template.ecf
docs/media/S4_template.ecf
docs/source/ecf.rst
docs/source/installation.rst
environment.yml
environment_pymc3.yml
setup.cfg
tests/MIRI_ecfs/S4_MIRI.ecf
tests/NIRCam_ecfs/S4_NIRCam.ecf
tests/NIRSpec_ecfs/S4_NIRSpec.ecf
tests/Photometry_NIRCam_ecfs/S4_Photometry_NIRCam.ecf
tests/WFC3_ecfs/S4_WFC3.ecf

This PR resolves #540
I've set a lower limit on the exotic-ld version to 3.1.2 which is their latest version (contains the updated post commissioning sensitivity files for JWST), and I've updated the documentation to make sure folks know how to download those reference files and know that the reference files change with different ExoTiC-LD reference files.

Updating instructions for newer exotic-ld versions

---

src/eureka/S5_lightcurve_fitting/fitters.py

Quick fix of issue #621 so that the emcee run can also continue from a white-light emcee chain run.
I used the same nomenclature (_channel_tag_) as in the `save_fit` function.

Fix emcee old_chain for white-light curve fit bug

---

docs/source/ecf.rst
src/eureka/S3_data_reduction/source_pos.py
src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py
src/eureka/S5_lightcurve_fitting/differentiable_models/StarryModel.py
src/eureka/S5_lightcurve_fitting/models/BatmanModels.py

The requirement for Ms was always a nuisance since it could potentially crash the code if Ms was larger than allowed by Kepler's 3rd law. The only reason it was added was so that starry would be able to accept both a/Rs and Porb, but Everett Schlawin pointed out to me that we can just set Mp=0 and then solve for Ms which is way easier and removes that nuisance parameter.
Some folks allow negative omega values, and sometimes its useful to use a prior like Intial Guess +/- 180 so that your fits don't end up bi-modal if they're near 0 or 360.
Finally, sometimes curve_fit will fail to converge with the default maxfev value, so I just increased it by 10x which solved my problems. Might be worth changing this to scipy.optimize.minimize and using Powell instead since that's been working so well …

Ms no longer used in starry models; batman `w` parameter no long must be between (0,360); minor tweaks

---

src/eureka/S3_data_reduction/bright2flux.py

This resolves #619
Rather than doing all of the reference file look-ups in the convert_to_e file, I've rearranged things so that the functions that need the reference files are the ones that look for them. This is simpler and keeps relevant pieces more localized.

Rearranging bright2flux ancillary file look-ups

---

environment.yml
environment_pymc3.yml
setup.cfg
src/eureka/S5_lightcurve_fitting/lightcurve.py
src/eureka/S5_lightcurve_fitting/likelihood.py
src/eureka/S5_lightcurve_fitting/models/BatmanModels.py
src/eureka/S5_lightcurve_fitting/models/CentroidModel.py
src/eureka/S5_lightcurve_fitting/models/GPModel.py
src/eureka/S5_lightcurve_fitting/models/LorentzianModel.py
src/eureka/S5_lightcurve_fitting/models/Model.py
src/eureka/S5_lightcurve_fitting/models/PoetModels.py
src/eureka/S5_lightcurve_fitting/models/PolynomialModel.py
src/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
src/eureka/S5_lightcurve_fitting/plots_s5.py
src/eureka/S5_lightcurve_fitting/s5_fit.py
src/eureka/S6_planet_spectra/s6_spectra.py
tests/MIRI_ecfs/s5_fit_par.epf
tests/Photometry_NIRCam_ecfs/S5_Photometry_NIRCam.ecf
tests/Photometry_NIRCam_ecfs/S5_fit_par.epf
tests/test_Photometry_NIRCam.py

Fixing new POET bugs and old bugs
Old bugs include issues with multwhite fits, masked values, and nbin_plot dealing with nbin_plot=len(time) in the presence of masked values.
New POET bugs include improperly handling multi-channel (or multwhite) fits (because only the values for channel 0 were ever used), and a broken alias between fp and fpfs.
Also fixing a bug in S6 related to load_model function.

Fixing new POET bugs, and old bugs with multwhite fits, masked values in fits, nbin_plot in S5, and S6 model loading

---

environment.yml
environment_pymc3.yml

Installing celerite2 and mc3 through conda on Apple M2 computers apparently fails (#635) but works when installing them through pip. This PR applies that small tweak to environment.yml and environment_pymc3.yml and resolves #635

Updating environment.yml files for Apple M2 computers

---

demos/JWST/S3_nircam_photometry_template.ecf
docs/source/ecf.rst
src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/lib/apphot.py
src/eureka/lib/disk.py
tests/Photometry_NIRCam_ecfs/S3_Photometry_NIRCam.ecf
tests/Photometry_NIRCam_ecfs/S3_Photometry_NIRCam_hex.ecf
tests/test_Photometry_NIRCam.py

This pull request adds in hexagonal apertures to the NIRCam photometry modes, since the defocused image is hexagonal (like the observatory main mirror), and not circular. Thanks to Ian for hacking on this in five minutes and coming up with something twice as fast as what I'd come up with.
This ended up being easy, just a drop-in replacement for the disk routine, and an added ECF parameter `aperture_shape` to control whether we're using circles or hexagons. This seems like it works as-is, but I haven't exhaustively tested it yet. I've also generalized the plotting code slightly to take advantage of this, and it looks like we get proper apertures in plot 3306 now.

Adding Hexagonal photometry apertures

---

.readthedocs.yaml
docs/source/installation.rst
docs/source/notebooks.rst
src/eureka/S1_detector_processing/update_saturation.py
src/eureka/S6_planet_spectra/s6_spectra.py

This tiny little PR fixes our Read the Docs pages. Since requiring Python >= 3.10 our docs page has apparently been failing to build since the .readthedocs.yml file was setup to use Python 3.9. I've tested this change and can confirm it resolves the issue.

Fixing our readthedocs pages

---

demos/JWST/S3_miri_lrs_template.ecf
environment.yml
environment_pymc3.yml
setup.cfg
src/eureka/S1_detector_processing/s1_process.py
src/eureka/lib/util.py

@erinmmay pointed out some issues with using the environment_pymc3.yml file on Apple silicon, and I confirmed the issue was impacting me as well on Intel Ubuntu. I worked on a solution with Erin over Slack that is confirmed to work for both of us at this point.
I also encountered some bugs with the S1 instrument-specific steps and the `lib.util.load_attrs_from_xarray()` function which I've patched. While I was at it, I also updated some of the default values for the MIRI/LRS S3 template

Bug patches

---

src/eureka/S5_lightcurve_fitting/differentiable_models/HSTRampModel.py

There was a bug in the HSTRamp differentiable model, which wasn't updated to the new parameters for setting the number of channels in `eval()`. This was throwing an error in S5 when using `starry` lightcurves. This was only an issue in this model, and the rest of the differentiable models look fine.

Bugfix in HSTRampModel, corrected nchan assignment

---

docs/source/ecf.rst
docs/source/faq.rst
docs/source/installation.rst
docs/source/quickstart.rst
src/eureka/S3_data_reduction/s3_reduce.py
src/eureka/S3_data_reduction/wfc3.py

Minor edits, warning users of a dependency conflict that will cause installation to fail when specifying both `jwst` and `pymc3`, as well as one warning users about potential issues with HST spatial scan observations of inconsistent numbers of exposures.

Minor documentation edits to reflect pre-1.0 testing

---

src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/wfc3.py

I took some time today to work out how to properly NaN pad all the relevant arrays in order to resolve #649. I've tested it on the same dataset as @jbrande was using before and find that the code now works well for me - please test it too Yoni.
While testing everything out, I found an unrelated issue with Fig 3308 for WFC3 spatial scanning data; since this figure is made before the 2D drift correction, the figure ends up look pretty awful. This might also end up affecting the optimal spectral extraction if `meddata` was used, but I'm not totally sure. I tried messing around with things to fix that issue as well, but nothing obvious that I tried worked. I tried running `optspex.clean_median_flux` after `inst.correct_drift2D` for WFC3 data, and the Fig 3308 figure looked differently bad, …

Handling missing scan segments in HST data

---

src/eureka/lib/util.py

Having Eureka! safely ignore TA-related FITS files that users may accidentally try to include.
This PR resolves #473

Ignore TA-related FITS files

---

src/eureka/S5_lightcurve_fitting/s5_fit.py

Fixing bug where we didn't correctly check if centroid_sy and centroid_sx existed. This was mentioned in #636

Fixing bug in s5_fit where centroid_sy loaded despite not existing

---

src/eureka/S3_data_reduction/background.py
src/eureka/S4_generate_lightcurves/plots_s4.py
src/eureka/S4_generate_lightcurves/s4_genLC.py

This functionality enables users to examine the background for trends without saving the full 2D background array (large file sizes!). Also makes plots of the background light curves in S4 for quick inspection.

Save background model at source position and stddev of background counts in S3, create background lightcurves in S4

---

src/eureka/S5_lightcurve_fitting/models/ExpRampModel.py
src/eureka/S5_lightcurve_fitting/models/Model.py

Fixes bug when first time array element is masked in exponential ramp fitting. (#730 )
Also addresses bug when making a final plot if using multwhite fitting with no shared parameters (was incorrectly setting the channel to 0 for all channels for this plot, mismatched time arrays caused problems). Edge case bug for sure, came up when trying to figure out why my exponential ramps weren't working and I had all the normally "shared" parameters fixed.

Addresses #730 and small multwhite bug

---

src/eureka/S5_lightcurve_fitting/models/AstroModel.py

Resolves #735
There was previously an error in the units used within a sin function call, where degrees were accidentally passed in instead of radians.

Fixing bug in light travel time calculation for circular orbit

---

src/eureka/S1_detector_processing/group_level.py
src/eureka/S1_detector_processing/s1_meta.py
src/eureka/S5_lightcurve_fitting/lightcurve.py
src/eureka/S5_lightcurve_fitting/plots_s5.py
src/eureka/lib/util.py

The recent PR that enabled the NIRISS pipeline made some important changes that didn't make it into Stage 1.  When running group-level BG subtraction, `meta.orders` and `meta.src_ypos` need to be specified.  
There was also an issue with how an Xarray was being created, such that it didn't have the necessary coordinates.
A big thanks to @astroRez for finding the issue and helping to come up with a solution.

Fixes bugs in Stage 1 GLBS due to recent PR

---

docs/source/installation.rst
src/eureka/S1_detector_processing/s1_meta.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S3_data_reduction/background.py
src/eureka/S3_data_reduction/s3_meta.py

Fixing S1 GLBS-related bugs
This PR resolves #763 and resolves #764
This PR also resolves an issue I was having with the recent tweaks to s3_meta.py with an out-of-limits issue from xwindow[1] and ywindow[1] being too large by 1, as well as some strange issue with `CubeModel` expecting inputs of a different size which was resolved by switching to the more generic `JwstDataModel`.
@kevin218, do you think it'd be worth issuing a v1.2.1 release with this PR or at least doing so quite soon? If so, I can update the docs pages to refer to v1.2.1 instead of v1.2

S1 background patches

---

src/eureka/S1_detector_processing/group_level.py
src/eureka/S1_detector_processing/s1_meta.py
src/eureka/S1_detector_processing/s1_process.py
src/eureka/S3_data_reduction/background.py
src/eureka/S3_data_reduction/miri.py
src/eureka/S3_data_reduction/plots_s3.py
src/eureka/S3_data_reduction/s3_meta.py
src/eureka/S4_generate_lightcurves/s4_genLC.py
src/eureka/S4_generate_lightcurves/s4_meta.py
src/eureka/S6_planet_spectra/s6_spectra.py
src/eureka/lib/manageevent.py
src/eureka/lib/readECF.py

I've been running some tests using MIRI that required specifying spectroscopic channels using a fixed number of pixel rows.  The tests were successful, so I'm adding this new functionality to the `main` branch.
I've also enabled RxR plus CxC BG subtraction for MIRI.  Similar to the 390hz feature, this effort didn't improve the resulting spectrum.
Finally, I fixed a small (but important) bug in Stage 6.  After relabeling `a0` to `rp` in the Harmonica Stage 5 code, I forgot to update Stage 6.

Adds number of pixel bins as option in S4

---

demos/JWST/S3_niriss_soss_template.ecf
docs/source/ecf.rst
src/eureka/S3_data_reduction/niriss.py
src/eureka/S3_data_reduction/s3_meta.py
src/eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
src/eureka/S5_lightcurve_fitting/s5_meta.py
src/eureka/S6_planet_spectra/s6_spectra.py
src/eureka/lib/readECF.py
src/eureka/lib/util.py

PASTASOSS only computes the trace for SUBSTRIP256, so we currently need to supply an offset.  The expected value is -10 pixels, but this can vary by a pixel or two.
I've made sure that Order 2 gets masked, even when only requesting the Order 1 spectrum.  Additionally, I've limited the Order 2 mask so that it doesn't interfere with the spectral extraction of Order 1.
Finally, I (hopefully) fixed the NIRISS MAD calculation.

Enables NIRISS SUBSTRIP96 mode

---

demos/JWST/S4_template.ecf
docs/media/S4_template.ecf
docs/source/ecf.rst
src/eureka/S4_generate_lightcurves/outliers.py
src/eureka/S4_generate_lightcurves/s4_meta.py

Previously relied on box_width which was in units of number of integrations, while mad_box_width should be in units of wavelength elements. The two shouldn't be forced to be the same

Add s4_meta.mad_box_width and update related calculations

---

src/eureka/S1_detector_processing/group_level.py

Stage 1 GLBS breaks without `skip_bg` defined.

Define skip_bg for Stage 1 GLBS
