kevin218/Eureka

.travis.yml, demos/LCFitting_Demo.py, eureka/lib/lsq.py, eureka/lightcurve_fitting/fitters.py, eureka/lightcurve_fitting/lightcurve.py, eureka/lightcurve_fitting/models.py, eureka/tests/test_lightcurve_fitting.py
=> pytest passes

eureka/S3_data_reduction/plots_s3.py, eureka/lib/savetable.py
Added two things that were missing from the last pull request:
- cleaned up savetable.py and added a bit of documentation to it
- a bug in plots_s3.py due to the renaming of ev.wave to ev.wave_1d and ev.wave_2d
=> updated savetable.py, fixed plots_s3.py

README.md, docs/source/installation.rst, docs/source/quickstart.rst
Changes:
- added brief installation instruction for Eureka! and docs link to README
- added installing instructions to docs (including installing setup.py)
=> updated README and docs

demos/S3/S4_template.ecf, eureka/S3_data_reduction/s3_reduce.py, eureka/S4_generate_lightcurves/drift.py, eureka/S4_generate_lightcurves/plots_s4.py, eureka/S4_generate_lightcurves/s4_genLC.py
- Added eureka/S4_generate_lightcurves/drift.py to copmute 1D drift
- Added drift plot to eureka/S4_generate_lightcurves/plots_s4.py
- Calling drift.py from eureka/S4_generate_lightcurves/s4_genLC.py
- New parameters in S4 ecf file
=> Add S4 drift correction

demos/S3/S3_template.ecf, demos/S3/S4_template.ecf, eureka/S2_calibrations/s2_calibrate.py, eureka/S3_data_reduction/background.py, eureka/S3_data_reduction/nirspec.py, eureka/S3_data_reduction/optspex.py, eureka/S3_data_reduction/s3_reduce.py, eureka/lib/util.py
- Moved Stage 2 NIRSpec code to s2_calibrate
- Computed bjdtdb for NIRSpec CV3 data
- Fewer integrations when testing S3
- Update ecf files
- Handle NaNs in NIRSpec data
=> NIRSpec Update

eureka/S3_data_reduction/s3_reduce.py
=> Make sure aperture values are explicit when running

demos/S5/S5_template.ecf, demos/S5/run_S5.py, eureka/S5_lightcurve_fitting/fitters.py, eureka/S5_lightcurve_fitting/lightcurve.py, eureka/S5_lightcurve_fitting/s5_fit.py
Hey Megan, I took a first stab at adding the plotting keywords like you'd requested. I also made some changes to the way the S5 ecf was read while I was at it to make things a bit easier on you. If you're happy with my edits, you can approve this and merge it into your s5_megan branch. I'm happy to help with the remaining issues with your PR on Monday if you want (especially the integration with S4). I'd love to start running S5 to see how tweaks to S1-4 end up impacting the overall retrieved transit spectra and whatnot.
=> Editing S5 to increase uniformity across stages

eureka/S5_lightcurve_fitting/fitters.py, eureka/S5_lightcurve_fitting/lightcurve.py, eureka/S5_lightcurve_fitting/s5_fit.py
I changed almost all of the print statements in S5 into logs as per Kevin's request so that S5's outputs are all saved. The only print statements remaining are those before the log file is created.
=> Changing S5 prints to logs

eureka/S5_lightcurve_fitting/models/Model.py
I accidentally added too many reload statements, one of which was not a valid use of the function which results in an error. I've corrected this now.
=> Removing incorrect use of reload

demos/S1/run_eureka.py, eureka/S1_detector_processing/__init__.py, eureka/S1_detector_processing/ramp_fitting.py, eureka/S1_detector_processing/s1_process.py, eureka/__init__.py
Adds Stage 1 capabilities to the pipeline, documentation to be written soon<sup>TM</sup>
- Tested for the NIRSpec, NIRISS, MIRI and NIRCam datasets (with help from Eva)
- Also fixes issue #102 by restructuring the s1_process.py file to match that of the other stages #102
=> Adding Stage 1

eureka/tests/test_lightcurve_fitting.py
minor fixes to function calls and arguments in test_exponentialmodel()
=> fix test_lightcurve_fitting.py for new exp model

requirements.txt
This should cover pyximport too
=> cython added to reqs

.gitignore, eureka/S3_data_reduction/__init__.py, pyproject.toml, setup.py
Needed to add some special code to the setup.py file to make sure that
the pyx file gets compiled and installed into the eureka site-package
=> Resolving niriss_cython import issues

eureka/S3_data_reduction/s3_reduce.py, eureka/S5_lightcurve_fitting/models/ExpRampModel.py, eureka/S5_lightcurve_fitting/models/Model.py, eureka/S5_lightcurve_fitting/models/PolynomialModel.py, eureka/S5_lightcurve_fitting/s5_fit.py
A quick little bug patch PR to resolve Yoni's 2 discovered issues #128 and #129
=> Resolving Issues #128 and #129

demos/Run_Eureka.ipynb, eureka/S5_lightcurve_fitting/fitters.py, eureka/S5_lightcurve_fitting/lightcurve.py, eureka/S5_lightcurve_fitting/likelihood.py, eureka/S5_lightcurve_fitting/plots_s5.py, eureka/S5_lightcurve_fitting/s5_fit.py, eureka/lib/lsq.py
- new fitting parameter: scatter_ppm
- parameter used for chi squared and log likelihood calculations
- make code robust to hitting upper or lower bound in initial lsq
- add a new plot: distribution of residuals normalized by the single-point scatter in the light curve
- fix xlabel for lc plot
- fix uncertainties in residuals panel following lc fit
=> add lc scatter as fit param + new residuals distribution plot + minor plot fixes

demos/JWST/S6_template.ecf, eureka/S5_lightcurve_fitting/limb_darkening_fit.py, eureka/S6_planet_spectra/plots_s6.py, eureka/S6_planet_spectra/s6_spectra.py
@taylorbell57 In case you're wondering what's up with `plots_s6.py`, I changed all the tabs to spaces for code indentation.  I also noticed that many other files used tabs.  When we first started, everything was supposed to use 4 spaces for indentation.  We need to figure out a consistent solution.
=> Minor enhancements to Stages 5 + 6

demos/JWST/S3_nirspec_fs_template.ecf, eureka/S3_data_reduction/plots_s3.py, eureka/S4_generate_lightcurves/plots_s4.py
resolves issue #142. Updated S3 ecf file for NIRSpec is a good starting point for getting decent light curves.
=> Addressed memory leak in S3/S4 plotting, new defaults for NIRSpec S3 ecf

demos/JWST/S3_miri_lrs_template.ecf, demos/JWST/S3_nircam_wfss_template.ecf, demos/JWST/S3_nirspec_fs_template.ecf, docs/media/S3_template.ecf, docs/source/ecf.rst, docs/source/quickstart.rst, eureka/S3_data_reduction/bright2flux.py, eureka/S3_data_reduction/miri.py, eureka/S3_data_reduction/nircam.py, eureka/S3_data_reduction/niriss.py, eureka/S3_data_reduction/nirspec.py, eureka/S3_data_reduction/plots_s3.py, eureka/S3_data_reduction/s3_reduce.py, eureka/S5_lightcurve_fitting/plots_s5.py, eureka/tests/NIRCam_ecfs/S3_NIRCam.ecf, eureka/tests/NIRSpec_ecfs/S3_NIRSpec.ecf
Closes #143 by using code already written in the jwst pipeline to determine the needed reference files and download them
=> Automating ancil file download

eureka/S4_generate_lightcurves/s4_genLC.py
Allowing user defined wavelength bins in Stage 4. This is beneficial to create outputs consistent with the requests of the ERS Data Challange
=> Allowing user defined wavelength bins in Stage 4

eureka/S4_generate_lightcurves/plots_s4.py, eureka/S5_lightcurve_fitting/lightcurve.py, eureka/S5_lightcurve_fitting/plots_s5.py, eureka/S5_lightcurve_fitting/s5_fit.py, eureka/S6_planet_spectra/plots_s6.py, eureka/S6_planet_spectra/s6_spectra.py
=> Masked arrays in S5

demos/JWST/S5_template.ecf, docs/media/S5_template.ecf, eureka/S5_lightcurve_fitting/fitters.py, eureka/S5_lightcurve_fitting/lightcurve.py, eureka/S5_lightcurve_fitting/likelihood.py, eureka/S5_lightcurve_fitting/models/BatmanModels.py, eureka/S5_lightcurve_fitting/plots_s5.py, eureka/S5_lightcurve_fitting/s5_fit.py, eureka/S5_lightcurve_fitting/utils.py, eureka/tests/NIRCam_ecfs/S5_NIRCam.ecf, eureka/tests/NIRSpec_ecfs/S5_NIRSpec.ecf
To make this happen, I needed to make a small number of tweaks.
First, the lc object no longer stores the log as this cannot be pickled.
Second, I had to remove all reload statements in Stage 5 as I could not
pickle reloaded classes (pickling is required for multiprocessing).
Finally, BatmanModels no longer store self.ld_func - if this is needed,
I can write more code later to allow ld_func to be pickled, but it is
currently unused and didn't seem worth the effort.
The number of threads is set in the S5 ecf, and if unset will default to
not running in parallel.
Also fixing merge conflict from PR #153. Also suppressing
EXOCTK_DATA warning (closes #177).
The full error message received when reload statements remain is
copied below:
> Traceback (most recent call last):
>   File …
=> Parallel processing in emcee and dynesty fitters

eureka/S5_lightcurve_fitting/models/SinusoidPhaseCurve.py
I'd accidentally forgotten to take the zeroth element of the 'ecc' and
'w' elements of the self.parameters.dict.
Credit for the edits goes to lcmayor.
=> Implementing lcmayor's bug patch

eureka/S4_generate_lightcurves/plots_s4.py
This closes #176 by putting the bin labels on a secondary x-axis like in the image below
=> Resolves #176 with a secondary x-axis

README.md, docs/media/S5_fit_par_template.ecf, docs/source/ecf.rst, docs/source/installation.rst
Added initial explainer for Stage 5 ECFs, still need explanations of the various transit/eclipse and systematics models. Added more info to clarify setting the CRDS environment variables.
=> Added Stage 5 Explainer, Updated CRDS env vars

README.md
Mildly broke the README formatting and have now fixed it.
=> Fixing slightly broken README formatting

eureka/S3_data_reduction/plots_s3.py, eureka/S3_data_reduction/s3_reduce.py, eureka/S4_generate_lightcurves/plots_s4.py, eureka/S4_generate_lightcurves/s4_genLC.py, eureka/lib/util.py
=> Moves MAD calculation out of plotting functions and into util.py

eureka/S5_lightcurve_fitting/fitters.py, eureka/S6_planet_spectra/s6_spectra.py
Also made the corresponding changes to the S6 read-in lines.
Closes #175 and merges in PR #174 along with this one
(We also should no longer need that temporary code I'd added in the saving file, so I removed it - it was just for reanalyzing some old S4 outputs of mine)
=> Adding zero padding to S5 save filenames

.github/ISSUE_TEMPLATE/blank_issue.yml, .github/ISSUE_TEMPLATE/bug-template.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/improvement-template.yml
Added questions asking for OS, Python version, list of installed Python packages
Made blank issue format for issues that don't fall under "bug" or "enhancement"
Removed question asking for contact info.
=> Add additional information to issue templates

eureka/S5_lightcurve_fitting/lightcurve.py, eureka/S5_lightcurve_fitting/plots_s5.py
=> Clearing all reused figures

eureka/S5_lightcurve_fitting/plots_s5.py
=> Making sure to use np.ma functions in S5 plots

docs/source/installation.rst
The old update instructions forced reinstalls which wasn't a necissary step. I'm also putting more emphasis on setting up a conda environment and the CRDS setup
=> Improving update instructions

demos/HST/run_eureka_wfc3.py, demos/JWST/run_eureka.py, eureka/S3_data_reduction/s3_reduce.py, eureka/S4_generate_lightcurves/s4_genLC.py, eureka/S5_lightcurve_fitting/s5_fit.py, tests/test_MIRI.py, tests/test_NIRCam.py, tests/test_NIRSpec.py, tests/test_WFC3.py
=> Renaming S3-5 main functions

eureka/S4_generate_lightcurves/s4_genLC.py
Use correct filename variable when load S3 outputs, update NIRSpec S1 FITS in tests
=> Squashing Bugs

docs/source/installation.rst, docs/source/quickstart.rst
=> Fixing quickstart typo

src/eureka/lib/manageevent.py
So the issue with datetime was still present, and I realized that the
metas were not being merged correctly. This has now been updated.
=> Fixing issue with datetime

src/eureka/S3_data_reduction/miri.py
=> Fixing time array for NGTS-10b MIRI new_drift files

src/eureka/S3_data_reduction/bright2flux.py, src/eureka/S3_data_reduction/miri.py, src/eureka/S3_data_reduction/nircam.py, src/eureka/S3_data_reduction/nirspec.py, src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/S3_data_reduction/wfc3.py, src/eureka/S4_generate_lightcurves/plots_s4.py, src/eureka/S4_generate_lightcurves/s4_genLC.py, src/eureka/S5_lightcurve_fitting/fitters.py, src/eureka/S5_lightcurve_fitting/lightcurve.py, src/eureka/S5_lightcurve_fitting/likelihood.py, src/eureka/S5_lightcurve_fitting/plots_s5.py, src/eureka/S6_planet_spectra/s6_spectra.py, src/eureka/lib/clipping.py, src/eureka/lib/manageevent.py, src/eureka/lib/util.py
This PR:
1. Fixes the allapers setting in Stages 4+ which was broken by my previous fix for datetime.
2. Fixes Stage 6 for lsq runs from Stage 5 (lack of error bars previously broke this)
3. Fixes broken allanplot in Stage 5 if sigma clipping was done in Stage 4
4. Does instart-1 once per file, rather than everywhere instart is used
5. Slightly tweaks S3+ log formatting to look a bit nicer
=> Bug patches and log tweaks

demos/HST/S3_wfc3_template.ecf, demos/HST/S4_wfc3_template.ecf, demos/JWST/S3_miri_lrs_template.ecf, demos/JWST/S3_nircam_wfss_template.ecf, demos/JWST/S3_nirspec_fs_template.ecf, demos/JWST/S4_template.ecf, docs/media/S3_template.ecf, docs/media/S4_template.ecf, docs/source/ecf.rst, src/eureka/S3_data_reduction/plots_s3.py, src/eureka/S4_generate_lightcurves/plots_s4.py, tests/MIRI_ecfs/S3_MIRI.ecf, tests/MIRI_ecfs/S4_MIRI.ecf, tests/NIRCam_ecfs/S3_NIRCam.ecf, tests/NIRCam_ecfs/S4_NIRCam.ecf, tests/NIRSpec_ecfs/S3_NIRSpec.ecf, tests/NIRSpec_ecfs/S4_NIRSpec.ecf, tests/WFC3_ecfs/S3_WFC3.ecf, tests/WFC3_ecfs/S4_WFC3.ecf
This PR allows setting vmin, vmax and choosing which axis is the time axis in figs 3101 and 4101.
Resolves #347
=> Figs 3101, 4101 tweaks

demos/HST/download_data_HST_template.py, demos/JWST/download_data_JWST_template.py, src/eureka/lib/mastDownload.py
This PR allows users to download JWST using the template provided in the demos directory.
=> Download JWST data

src/eureka/S3_data_reduction/plots_s3.py, src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/S3_data_reduction/source_pos.py, src/eureka/S3_data_reduction/wfc3.py, src/eureka/lib/util.py
The real observations have NaNs all over the place from being masked out
in earlier stages, and these were not handled properly in source_pos.py
=> Fixing NaNs in source_pos with real data

demos/HST/download_data_HST_template.py, demos/JWST/download_data_JWST_template.py, src/eureka/lib/mastDownload.py
Enhancements to data download scripts based on yesterday's experience downloading JWST data.
=> Enhance data download scripts

src/eureka/S1_detector_processing/ramp_fitting.py, src/eureka/S2_calibrations/s2_calibrate.py
Quick fix for issue #396
Haven't had the time to *fully* check this through Stage 3 yet, but I can see that the INT_TIMES is correctly populated after Stage 1. Will take a proper look tomorrow but wanted to put the PR in anyway.
=> Resolve issue with blank int_times + fix NIRspec disp axis trimming

src/eureka/S3_data_reduction/bright2flux.py
=> fix for gain files that aren't full frame

src/eureka/S3_data_reduction/background.py, src/eureka/S3_data_reduction/nircam.py, src/eureka/S3_data_reduction/optspex.py, src/eureka/S3_data_reduction/plots_s3.py, src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/S3_data_reduction/straighten.py, tests/WFC3_ecfs/S3_WFC3.ecf, tests/WFC3_ecfs/S4_WFC3.ecf, tests/test_WFC3.py
Curvature plot was sensitive to bad pixels, so I smoothed the results first.  Also added a new plot (3106) to demonstrate the measured curvature.  Also, fixed a few loose ends from previous PR.
=> Smooth curvature, compute clean median flux

src/eureka/S1_detector_processing/s1_process.py, src/eureka/S2_calibrations/s2_calibrate.py, src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/S4_generate_lightcurves/s4_genLC.py, src/eureka/S5_lightcurve_fitting/s5_fit.py, src/eureka/S6_planet_spectra/s6_spectra.py, src/eureka/lib/readECF.py
To make it easier to use Eureka! in notebooks and interactively we added a parameter input_meta to every Stage to allow for users to pass meta without loading an .ecf file (See ERS_NIRCam notebook). 
I also added some lines to replace meta.lines in the ecf class if parameters have changed.
=> Add input_meta parameter to every Stage and update write function

.github/workflows/draft-pdf.yml, .github/workflows/flake8_linting.yml, .github/workflows/pytest_testing.yml, docs/source/installation.rst, setup.cfg
Simply incrementing docs to point to the new v0.9 (I will make v0.9 once this PR is merged).
=> Updating docs to v0.9

src/eureka/S3_data_reduction/plots_s3.py
Isaac and I noticed a couple of plotting bugs (one from Isaac's PR, and two from some long ago PR) that were super easy to fix quickly. Let's fix them with this PR before v0.9
=> Fixing S3 plotting bugs

README.md, docs/source/index.rst, environment.yml, environment_pymc3.yml, setup.cfg, src/eureka/S3_data_reduction/plots_s3.py, src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/lib/centerdriver.py, src/eureka/lib/clipping.py, src/eureka/lib/gaussian_min.py
This PR has some minor bug fixes. Specifically, it fixes some small bugs with S3 photometry code, and it fixed a bug where setting fill_value to 'boxcar' in Stage 4 still resulted in points being masked while they should've been left unmasked and simply replaced with the value from the boxcar smoothed data.
=> Minor bug fixes

environment.yml, environment_pymc3.yml, setup.cfg
=> Add matplotlib lower limit to installation

docs/source/quickstart.rst
Issue #562 asked for some HST quickstart info. I've added an extra section to the quickstart docs page to explain this a little, and if needed can expand this in more detail.
=> Added short quickstart text about HST operations

src/eureka/S3_data_reduction/optspex.py, src/eureka/S5_lightcurve_fitting/fitters.py
Fixing two bugs in S3's optspex.py file pointed out by @kevin218, and also fixing a bug I encountered in S5 related to the new `meta.expand` variable (which only happens if you run the new S5 on old S4 data).
=> Fixing minor bugs recently introduced

demos/HST/s5_fit_par_wfc3_template.epf, demos/JWST/S5_fit_par_template.epf, demos/JWST/S5_template.ecf, docs/media/S5_fit_par_template.epf, docs/media/S5_template.ecf, docs/source/ecf.rst, src/eureka/S5_lightcurve_fitting/differentiable_models/PyMC3Models.py, src/eureka/S5_lightcurve_fitting/fitters.py, src/eureka/S5_lightcurve_fitting/lightcurve.py, src/eureka/S5_lightcurve_fitting/likelihood.py, src/eureka/S5_lightcurve_fitting/models/BatmanModels.py, src/eureka/S5_lightcurve_fitting/models/GPModel.py, src/eureka/S5_lightcurve_fitting/models/Model.py, src/eureka/S5_lightcurve_fitting/plots_s5.py, src/eureka/S5_lightcurve_fitting/s5_fit.py, tests/MIRI_ecfs/s5_fit_par_starry.epf, tests/NIRCam_ecfs/S5_fit_par.epf, tests/NIRSpec_ecfs/S5_fit_par.epf
There were numerous bugs with the current GP model; this PR brings the GP model back to working order for individual fits and makes it so that the GP model can also be used for shared or multwhite fits.
Resolves #555
The GPModel.py file was long neglected and had numerous bugs in it, some of which were from updates to other models. I've significantly cleaned up the code and changed the fitted GP variables. So far I've tested this with success on a single photometric lightcurve as well as a multwhite fit of two photometric lightcurves. It can be a bit tricky to get the optimizer to converge when doign a multwhite fit, but that's to be expected and the underlying code works (successfully run with lsq).
The only outstanding thing to be done before this PR is ready for review is updating the …
=> Fixing the S5 GP Model

src/eureka/S3_data_reduction/plots_s3.py, src/eureka/S4_generate_lightcurves/plots_s4.py, src/eureka/S5_lightcurve_fitting/lightcurve.py, src/eureka/S5_lightcurve_fitting/models/KeplerOrbit.py, src/eureka/S5_lightcurve_fitting/plots_s5.py, src/eureka/S6_planet_spectra/plots_s6.py, src/eureka/lib/plots.py
This should resolve #529 and also tidies up the code some
=> Switching plots from tight_layout to constrained_layout

src/eureka/S5_lightcurve_fitting/differentiable_models/GPModel.py, src/eureka/S5_lightcurve_fitting/models/GPModel.py
To fix the issue with masked data causing the GP model to fail, I've copied the code from the GP likelihood function which removed the masked data, and in the eval function I just add back masked zeros where there were masked values.
This PR pesolves #645
=> Fixing issue where GP model with masked data failed

src/eureka/S5_lightcurve_fitting/plots_s5.py
Quick fix to get the Allan variance plot working.
=> Fix check on time_avg

src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/S6_planet_spectra/s6_spectra.py
This little PR resolves the issue where Stage 6 plots malfunctioned for the case where some variables were getting confused by the S6 code. Additionally, I added a small patch to make sure that the default `meta.aperture_shape` was applied early enough in the code
=> Bug Patch: S6 with similar variable names and S3 undefined aperture_shape

src/eureka/S5_lightcurve_fitting/s5_fit.py, src/eureka/S6_planet_spectra/plots_s6.py, src/eureka/S6_planet_spectra/s6_spectra.py
This small PR skips fully masked channels in Stage 5, and then adjusts the Stage 6 code to cope with skipped channels from Stage 5.
This PR resolves #546
=> Adding the ability to skip fully-masked data in Stage 5-6

demos/JWST/S1_nirx_template.ecf, demos/JWST/S2_nircam_wfss_template.ecf, demos/JWST/S3_nircam_wfss_template.ecf, demos/JWST/S4_template.ecf, src/eureka/S4_generate_lightcurves/generate_LD.py, src/eureka/S4_generate_lightcurves/plots_s4.py
The changes to the NIRCam ECFs are mostly cosmetic, but this PR also includes an important bug fix in Stage 4.
=> NIRCam enhancements from v1 testing

demos/HST/S6_wfc3_template.ecf, demos/JWST/S6_template.ecf, docs/media/S6_template.ecf, docs/source/ecf.rst, src/eureka/S3_data_reduction/miri.py, src/eureka/S3_data_reduction/s3_meta.py, src/eureka/S3_data_reduction/wfc3.py, src/eureka/S6_planet_spectra/s6_meta.py, src/eureka/S6_planet_spectra/s6_spectra.py, src/eureka/lib/util.py
The first resolves #675 and the second resolves #655.
=> Two Enhancements from Testing v1.0

src/eureka/S6_planet_spectra/s6_spectra.py
In my previous PR, I forgot to recalculate the nightside flux for POET.
=> Compute nightside flux with POET

demos/JWST/S3_miri_photometry_template.ecf, demos/JWST/S3_nircam_wfss_template.ecf, environment.yml, environment_pymc3.yml, setup.cfg, src/eureka/S1_detector_processing/group_level.py, src/eureka/S3_data_reduction/plots_s3.py, src/eureka/S6_planet_spectra/s6_spectra.py, src/eureka/lib/centerdriver.py
This PR has a few last minor bug patches before we release version 1.0
=> Minor bug patches before v1.0

src/eureka/S3_data_reduction/plots_s3.py
Labelling WFC3 scan directions in Fig 3106, using code based on that suggested by @astroRez 
This PR resolves #709
=> Labelling WFC3 scan directions in Fig 3106

src/eureka/S3_data_reduction/nirspec.py, src/eureka/S3_data_reduction/optspex.py, src/eureka/S6_planet_spectra/s6_spectra.py, src/eureka/lib/mastDownload.py
This tiny PR fixes the JWST download script because it was broken and also fixes a few minor typos.
=> Update download script

docs/source/ecf.rst
=> Improving documentation of bg_x1 and bg_x2

src/eureka/lib/util.py
This is a quick fix for a bug that I introduced in a recent PR.  I'm genuinely shocked that the code didn't break during testing.
=> Fixes small bug in binData_time

src/eureka/S5_lightcurve_fitting/s5_fit.py
=> Editing s5_fit to load latest saved white LC, like in manageevent.findevent()

src/eureka/S5_lightcurve_fitting/models/StepModel.py
Not sure if this is the most efficient way to fix this bug (based on how ExpRampModel is set up), but I've tested that it works. 
It might have to be tested for higher python versions (I used Python 3.9.7) but I hope this works!
Addresses issue https://github.com/kevin218/Eureka/issues/774
=> Fix bug for multwhite fitting when using StepModel

src/eureka/S3_data_reduction/s3_meta.py, src/eureka/S3_data_reduction/s3_reduce.py, src/eureka/lib/apphot.py
=> Update photap_b handling for circular apertures in S3 reduction
